global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "edo-adapter-api"
    static_configs:
      - targets: ["api:8099"]
    metrics_path: /api/v1/health/metrics

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
